import { Platypi } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const platypi = Platypi({
  display: "swap",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>BURGER</title>
        <link rel="icon" href="/burger.png" sizes="16x16" />
      </head>
      <body className={platypi.className}>{children}</body>
    </html>
  );
}
